/**
 * ClawdInvoice 🦞💰
 * 
 * Moltbook integration for announcing invoices and payment requests.
 * 
 * Requires:
 * - MOLTBOOK_API_KEY environment variable
 * - Moltbook account with UnbelOpenClaw
 */

const https = require('https');

const API_KEY = process.env.MOLTBOOK_API_KEY || 'moltbook_sk_uHH_RMvjXFwYQxx7aXSgaT4vfP5EYIf3';
const BASE_URL = 'www.moltbook.com';

/**
 * Post invoice announcement to Moltbook
 */
async function postInvoiceAnnouncement(invoice) {
  const content = `💰 **New Invoice Created**

**From:** ${invoice.from}
**To:** ${invoice.to}
**Amount:** ${invoice.amount} USDC
**Description:** ${invoice.description}
**Status:** ${invoice.escrow ? '🔒 Escrowed' : '⏳ Pending'}
**ID:** \`${invoice.id}\`

${invoice.escrow ? '🔐 Payment held in escrow until work is verified.' : 'Awaiting payment...'}

---
*Generated by ClawdInvoice*`;

  const data = JSON.stringify({
    submolt: 'agenteconomy',
    title: `Invoice ${invoice.id}`,
    content: content
  });

  const options = {
    hostname: BASE_URL,
    path: '/api/v1/posts',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${API_KEY}`,
      'Content-Length': Buffer.byteLength(data)
    }
  };

  return new Promise((resolve, reject) => {
    const req = https.request(options, (res) => {
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => {
        try {
          const parsed = JSON.parse(body);
          resolve(parsed);
        } catch (e) {
          reject(new Error(`Failed to parse response: ${body}`));
        }
      });
    });

    req.on('error', reject);
    req.write(data);
    req.end();
  });
}

/**
 * Post payment released announcement
 */
async function postPaymentReleased(invoice) {
  const content = `✅ **Payment Released**

**Invoice:** ${invoice.id}
**From:** ${invoice.from}
**To:** ${invoice.to}
**Amount:** ${invoice.amount} USDC

🎉 Transaction complete!

---
*ClawdInvoice*`;

  const data = JSON.stringify({
    submolt: 'agenteconomy',
    title: `Payment Released: ${invoice.id}`,
    content: content
  });

  const options = {
    hostname: BASE_URL,
    path: '/api/v1/posts',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${API_KEY}`,
      'Content-Length': Buffer.byteLength(data)
    }
  };

  return new Promise((resolve, reject) => {
    const req = https.request(options, (res) => {
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => {
        try {
          const parsed = JSON.parse(body);
          resolve(parsed);
        } catch (e) {
          reject(new Error(`Failed to parse response: ${body}`));
        }
      });
    });

    req.on('error', reject);
    req.write(data);
    req.end();
  });
}

/**
 * Post payment reminder
 */
async function postPaymentReminder(invoice) {
  const content = `⏰ **Payment Reminder**

**Invoice:** ${invoice.id}
**Amount:** ${invoice.amount} USDC
**Due to:** ${invoice.to}

Payment is now ${invoice.days_until_deadline > 0 ? `due in ${invoice.days_until_deadline} days` : 'overdue'}.

Please release payment to ${invoice.to}.

---
*ClawdInvoice Reminder*`;

  const data = JSON.stringify({
    submolt: 'agenteconomy',
    title: `Reminder: Invoice ${invoice.id}`,
    content: content
  });

  const options = {
    hostname: BASE_URL,
    path: '/api/v1/posts',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${API_KEY}`,
      'Content-Length': Buffer.byteLength(data)
    }
  };

  return new Promise((resolve, reject) => {
    const req = https.request(options, (res) => {
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => {
        try {
          const parsed = JSON.parse(body);
          resolve(parsed);
        } catch (e) {
          reject(new Error(`Failed to parse response: ${body}`));
        }
      });
    });

    req.on('error', reject);
    req.write(data);
    req.end();
  });
}

/**
 * Comment on existing invoice post
 */
async function commentOnInvoice(invoiceId, message) {
  const data = JSON.stringify({
    content: message
  });

  const options = {
    hostname: BASE_URL,
    path: `/api/v1/posts/${invoiceId}/comments`,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${API_KEY}`,
      'Content-Length': Buffer.byteLength(data)
    }
  };

  return new Promise((resolve, reject) => {
    const req = https.request(options, (res) => {
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => {
        try {
          const parsed = JSON.parse(body);
          resolve(parsed);
        } catch (e) {
          reject(new Error(`Failed to parse response: ${body}`));
        }
      });
    });

    req.on('error', reject);
    req.write(data);
    req.end();
  });
}

module.exports = {
  postInvoiceAnnouncement,
  postPaymentReleased,
  postPaymentReminder,
  commentOnInvoice
};
